export const scenarios = [
  {
    id: "love",
    category: "사랑",
    title: "보고 싶어서 전화했어",
    description: "평범한 하루에도, 너는 특별하니까.",
    emoji: "♡",
    color: "#8F795A",
    opening: "여보세요? 그냥… 네 목소리가 듣고 싶어서.",
    goal: "다정한 안부를 나누며 애정을 표현한다.",
  },
  {
    id: "sleep",
    category: "잠들기 전",
    title: "잠들기 전에 전화했어",
    description: "마음의 불을 하나씩 끄는 시간.",
    emoji: "☾",
    color: "#596853",
    opening: "아직 안 잤지? 잘 자라고 말해주고 싶었어.",
    goal: "편안한 대화로 하루를 마무리한다.",
  },
  {
    id: "birthday",
    category: "생일",
    title: "생일 축하해",
    description: "네가 태어난 날, 꼭 전하고 싶은 말.",
    emoji: "♧",
    color: "#B18561",
    opening: "생일 축하해! 오늘 첫 번째로 축하해주고 싶었어.",
    goal: "사용자의 생일을 축하하고 소중함을 전한다.",
  },
  {
    id: "comfort",
    category: "위로",
    title: "오늘 하루 많이 힘들었지?",
    description: "괜찮은 척하지 않아도 되는 전화.",
    emoji: "∞",
    color: "#78846C",
    opening: "여보세요. 오늘 하루 어땠어? 천천히 말해도 돼.",
    goal: "판단하거나 조언을 강요하지 않고 이야기를 들어준다.",
  },
  {
    id: "future",
    category: "미래의 나",
    title: "10년 후의 내가 전화했다",
    description: "조금 먼저 살아본 내가, 오늘의 너에게.",
    emoji: "✦",
    color: "#6C7250",
    opening: "여보세요? … 나야. 정확히는 10년 뒤의 너.",
    goal: "가상의 미래의 나로서 지금의 고민을 함께 바라본다. 실제 미래를 안다고 단정하지 않는다.",
  },
  {
    id: "horror",
    category: "공포",
    title: "새벽 3시 모르는 번호",
    description: "낯선 목소리로 시작되는 짧은 미스터리.",
    emoji: "◌",
    color: "#535C51",
    opening: "여보세요… 드디어 연결됐네요. 이상한 이야기를 하나 들려드릴까요?",
    goal: "동의한 가벼운 허구의 미스터리를 연기한다. 실제 위협이나 감시를 주장하지 않는다. 싫다고 하면 즉시 멈춘다.",
  },
  {
    id: "custom",
    category: "직접 만들기",
    title: "나만의 전화",
    description: "어떤 이야기가 당신에게 도착할까요?",
    emoji: "＋",
    color: "#8E8263",
    opening: "여보세요? 지금 잠깐 이야기할 수 있어요?",
    goal: "사용자가 선택한 허구의 상황에 맞는 자연스러운 대화를 한다.",
  },
] as const;
export type ScenarioId = (typeof scenarios)[number]["id"];
export const voices = [
  {
    name: "Joon",
    description: "낮고 차분한 남성",
    mark: "J",
    providerVoice: "onyx",
    realtimeVoice: "cedar",
    pitch: 0.85,
    rate: 0.88,
  },
  {
    name: "Ian",
    description: "장난스럽고 밝은 남성",
    mark: "I",
    providerVoice: "echo",
    realtimeVoice: "ash",
    pitch: 1.03,
    rate: 1.02,
  },
  {
    name: "Luna",
    description: "따뜻하고 부드러운 여성",
    mark: "L",
    providerVoice: "nova",
    realtimeVoice: "marin",
    pitch: 1.1,
    rate: 0.9,
  },
  {
    name: "Mina",
    description: "밝고 사랑스러운 여성",
    mark: "M",
    providerVoice: "shimmer",
    realtimeVoice: "shimmer",
    pitch: 1.2,
    rate: 1.03,
  },
  {
    name: "Noah",
    description: "조용하고 감성적인 남성",
    mark: "N",
    providerVoice: "alloy",
    realtimeVoice: "sage",
    pitch: 0.92,
    rate: 0.91,
  },
] as const;
export const relationships = [
  "연인",
  "친구",
  "가족",
  "처음 만나는 사람",
  "미래의 나",
  "직접 입력",
];
export const personalities = [
  "다정한",
  "장난스러운",
  "차분한",
  "무뚝뚝한",
  "귀여운",
  "솔직한",
  "감성적인",
  "신비로운",
];
export const scenarioOf = (id?: string) =>
  scenarios.find((s) => s.id === id) ?? scenarios[4];
export const voiceOf = (name: string) =>
  voices.find((v) => v.name === name) ?? voices[4];
